---
name: Run tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['master']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install yamllint
      - run: python lint.py
